# This workflow takes files in your folders and pushes them to the designated ServiceNow instance
# Ensure that you have configured the following secrets for this repository: INSTANCE_NAME, ADMIN_USERNAME, ADMIN_PASSWORD

name: Record event

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    paths:
      - '*/**'
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Log payload
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
    - name: Contact Instance
      id: myRequest
      uses: fjogeleit/http-request-action@v1.8.1
      with:
        url: ${{ format('https://{0}.service-now.com/api/x_snc_cc_git_table/githubtableloader', secrets.INSTANCE_NAME) }}
        method: 'POST'
        contentType: application/json
        data: ${{ toJson(github) }}
        username: ${{ secrets.ADMIN_USERNAME }}
        password: ${{ secrets.ADMIN_PASSWORD }}
    - name: Show Response
      run: echo ${{ steps.myRequest.outputs.response }}
